<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Carbon\Carbon;

class OfertaDetalleSeeder extends Seeder
{
    public function run()
    {
        DB::table('oferta_detalles')->insert([
            [
                'id_oferta' => 1,
                'id_produccion' => 1, // Valor de id_produccion correspondiente
                'id_unidadmedida' => 1,
                'id_moneda' => 1,
                'descripcion' => 'Detalle de oferta 1',
                'cantidad_fisico' => 3000,
                'cantidad_comprometido' => 0,
                'precio' => 103.52,
                'preciounitario' => 3.04,
                'estado' => 'activo',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id_oferta' => 2,
                'id_produccion' => 2,
                'id_unidadmedida' => 2,
                'id_moneda' => 2,
                'descripcion' => 'Detalle de oferta 2',
                'cantidad_fisico' => 5000,
                'cantidad_comprometido' => 0,
                'precio' => 58.36,
                'preciounitario' => 0.64,
                'estado' => 'activo',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id_oferta' => 3,
                'id_produccion' => 3,
                'id_unidadmedida' => 2,
                'id_moneda' => 2,
                'descripcion' => 'Detalle de oferta 3',
                'cantidad_fisico' => 10000,
                'cantidad_comprometido' => 0,
                'precio' => 100.57,
                'preciounitario' => 4.02,
                'estado' => 'activo',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id_oferta' => 4,
                'id_produccion' => 4,
                'id_unidadmedida' => 2,
                'id_moneda' => 2,
                'descripcion' => 'Detalle de oferta 4',
                'cantidad_fisico' => 500,
                'cantidad_comprometido' => 0,
                'precio' => 113.60,
                'preciounitario' => 1.77,
                'estado' => 'activo',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id_oferta' => 5,
                'id_produccion' => 5,
                'id_unidadmedida' => 2,
                'id_moneda' => 1,
                'descripcion' => 'Detalle de oferta 5',
                'cantidad_fisico' => 3500,
                'cantidad_comprometido' => 0,
                'precio' => 137.09,
                'preciounitario' => 3.18,
                'estado' => 'activo',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id_oferta' => 6,
                'id_produccion' => 6,
                'id_unidadmedida' => 1,
                'id_moneda' => 1,
                'descripcion' => 'Detalle de oferta 6',
                'cantidad_fisico' => 4000,
                'cantidad_comprometido' => 0,
                'precio' => 99.99,
                'preciounitario' => 1.78,
                'estado' => 'activo',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id_oferta' => 7,
                'id_produccion' => 7,
                'id_unidadmedida' => 1,
                'id_moneda' => 1,
                'descripcion' => 'Detalle de oferta 7',
                'cantidad_fisico' => 3100,
                'cantidad_comprometido' => 0,
                'precio' => 200.50,
                'preciounitario' => 1.67,
                'estado' => 'activo',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id_oferta' => 8,
                'id_produccion' => 8,
                'id_unidadmedida' => 2,
                'id_moneda' => 2,
                'descripcion' => 'Detalle de oferta 8',
                'cantidad_fisico' => 9000,
                'cantidad_comprometido' => 0,
                'precio' => 75.25,
                'preciounitario' => 1.00,
                'estado' => 'activo',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id_oferta' => 9,
                'id_produccion' => 9,
                'id_unidadmedida' => 1,
                'id_moneda' => 1,
                'descripcion' => 'Detalle de oferta 9',
                'cantidad_fisico' => 15000,
                'cantidad_comprometido' => 0,
                'precio' => 110.30,
                'preciounitario' => 1.11,
                'estado' => 'activo',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id_oferta' => 10,
                'id_produccion' => 10,
                'id_unidadmedida' => 2,
                'id_moneda' => 2,
                'descripcion' => 'Detalle de oferta 10',
                'cantidad_fisico' => 20000,
                'cantidad_comprometido' => 0,
                'precio' => 50.75,
                'preciounitario' => 1.69,
                'estado' => 'activo',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
        ]);
    }
}
