<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Carbon\Carbon;

class ProduccionSeeder extends Seeder
{
    public function run()
    {
        DB::table('produccions')->insert([
            [
                'id_terreno' => 1,
                'id_temporada' => 3,
                'id_producto' => 2,
                'id_unidadmedida' => 1,
                'descripcion' => 'Producción de ejemplo 1',
                'cantidad' => 17811,
                'fecha_cosecha' => '2024-10-28',
                'fecha_expiracion' => '2025-01-10',
                'estado' => 'activo',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id_terreno' => 2,
                'id_temporada' => 2,
                'id_producto' => 3,
                'id_unidadmedida' => 1,
                'descripcion' => 'Producción de ejemplo 2',
                'cantidad' => 3618,
                'fecha_cosecha' => '2024-10-02',
                'fecha_expiracion' => '2025-01-28',
                'estado' => 'activo',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id_terreno' => 1,
                'id_temporada' => 1,
                'id_producto' => 1,
                'id_unidadmedida' => 1,
                'descripcion' => 'Producción de ejemplo 3',
                'cantidad' => 13122,
                'fecha_cosecha' => '2024-10-31',
                'fecha_expiracion' => '2025-03-25',
                'estado' => 'activo',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id_terreno' => 2,
                'id_temporada' => 2,
                'id_producto' => 1,
                'id_unidadmedida' => 1,
                'descripcion' => 'Producción de ejemplo 4',
                'cantidad' => 28128,
                'fecha_cosecha' => '2024-08-21',
                'fecha_expiracion' => '2025-04-24',
                'estado' => 'activo',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id_terreno' => 1,
                'id_temporada' => 2,
                'id_producto' => 3,
                'id_unidadmedida' => 1,
                'descripcion' => 'Producción de ejemplo 5',
                'cantidad' => 31842,
                'fecha_cosecha' => '2024-10-09',
                'fecha_expiracion' => '2025-03-03',
                'estado' => 'activo',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id_terreno' => 3,
                'id_temporada' => 1,
                'id_producto' => 2,
                'id_unidadmedida' => 1,
                'descripcion' => 'Producción de ejemplo 6',
                'cantidad' => 24250,
                'fecha_cosecha' => '2024-09-15',
                'fecha_expiracion' => '2025-02-10',
                'estado' => 'activo',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id_terreno' => 1,
                'id_temporada' => 1,
                'id_producto' => 3,
                'id_unidadmedida' => 1,
                'descripcion' => 'Producción de ejemplo 7',
                'cantidad' => 19420,
                'fecha_cosecha' => '2024-10-05',
                'fecha_expiracion' => '2025-01-15',
                'estado' => 'activo',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id_terreno' => 3,
                'id_temporada' => 3,
                'id_producto' => 1,
                'id_unidadmedida' => 1,
                'descripcion' => 'Producción de ejemplo 8',
                'cantidad' => 40420,
                'fecha_cosecha' => '2024-08-28',
                'fecha_expiracion' => '2025-01-20',
                'estado' => 'activo',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id_terreno' => 2,
                'id_temporada' => 1,
                'id_producto' => 2,
                'id_unidadmedida' => 1,
                'descripcion' => 'Producción de ejemplo 9',
                'cantidad' => 21420,
                'fecha_cosecha' => '2024-10-14',
                'fecha_expiracion' => '2025-03-11',
                'estado' => 'activo',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id_terreno' => 1,
                'id_temporada' => 2,
                'id_producto' => 3,
                'id_unidadmedida' => 1,
                'descripcion' => 'Producción de ejemplo 10',
                'cantidad' => 33420,
                'fecha_cosecha' => '2024-09-10',
                'fecha_expiracion' => '2025-04-01',
                'estado' => 'activo',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ]
        ]);
    }
}
